/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// globals.h
/// Autogenerated by firmware-libraries/SerialComms/python/telem_file_generator.py on Sun Jan 17 17:30:14 2021

#ifndef INC_GLOBALS_H_
#define INC_GLOBALS_H_
#include <stdint.h>

extern uint32_t valve_states;
extern float e_batt;
extern float i_batt;
extern enum States STATE;
extern float e3v;
extern float e5v;
extern float i5v;
extern float i3v;
extern uint8_t last_command_id;
extern uint64_t micros;
extern uint32_t telem_rate;
extern uint32_t adc_rate;
extern uint8_t own_board_addr;
extern float pressure[6];
extern float ivlv[9];
extern float evlv[9];
extern float tc[5];
extern float i_mtr_ab[4];
extern float i_mtr[2];
extern float epot[4];

/// END AUTOGENERATED SECTION - USER CODE GOES BELOW THIS LINE

enum States {
    Idle    = 0,
    Armed   = 1,
    Running = 2,
    Stop    = 3
};

typedef struct Stepper_Ramping {
    // base variables
    uint16_t v_0;
    uint16_t v;
    uint16_t a;
    uint16_t F; // timer frequency
    // calculated parameters
    double S;
    double p1;
    double ps;
    double R;
    double p;
} Stepper_Ramping;


#define TELEM_PACKET_SIZE 254
extern uint8_t telem_packet[TELEM_PACKET_SIZE];

#endif /*INC_GLOBALS_H*/
