/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// pt_calibrations.h
/// Autogenerated by pt_calibration_generator.py on Sat Jan  2 20:58:29 2021

double pt_slope[19];

double pt_offset[19];