/// BEGIN AUTOGENERATED SECTION - MODIFICATIONS TO THIS CODE WILL BE OVERWRITTEN

/// globals.c
/// Autogenerated by firmware-libraries/SerialComms/python/telem_file_generator.py on Sun Jan 17 17:30:14 2021
#include "globals.h"

uint32_t valve_states = 0;
float e_batt = 0;
float i_batt = 0;
enum States STATE = 0;
float e3v = 0;
float e5v = 0;
float i5v = 0;
float i3v = 0;
uint8_t last_command_id = 0;
uint64_t micros = 0;
uint32_t telem_rate = 0;
uint32_t adc_rate = 0;
uint8_t own_board_addr = 3;
float pressure[6] = {0};
float ivlv[9] = {0};
float evlv[9] = {0};
float tc[5] = {0};
float i_mtr_ab[4] = {0};
float i_mtr[2] = {0};
float epot[4] = {0};

/// END AUTOGENERATED SECTION - USER CODE GOES BELOW THIS LINE

// Short Telem Packet
uint8_t telem_packet[TELEM_PACKET_SIZE] = {0};
